### ISSUE TITLE
Host images on hub.docker.com

### ISSUE THREAD

**Issue by cdlm** [pharo-project/pharo-docker#2]
There are already two related user accounts: [pharo](https://hub.docker.com/u/pharo/) and [pharoproject](https://hub.docker.com/u/pharoproject/)…

I created a [pharo organization on hub.docker.com](https://hub.docker.com/u/pharosmalltalk/) which we can use immediately, but I will retire it in favor of one of the above if we find the owner…

**Comment by mikefilonov** [comment]
Hey @cdlm,

Both accounts you mentioned are registered by me :) pharo is an organization and pharoproject is a user registered on community-owned email (docker@pharo.org) that is an owner of "pharo" organization.

That is exactly the goal to host these images at dockerhub with names like pharo/pharo:tag. And even more – to go up to official repositories, so our images accessible via "docker run pharo:60"

**Comment by cdlm** [comment]
Cool. Unfortunately deleting an organization only works via bother-a-human-on-support-forum-protocol…
